#ifndef LIB_WASM_H_GENERATED_
#define LIB_WASM_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
extern void (*Z_wasi_snapshot_preview1Z_proc_exitZ_vi)(u32);
/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_args_sizes_getZ_iii)(u32, u32);
/* import: 'wasi_snapshot_preview1' 'args_get' */
extern u32 (*Z_wasi_snapshot_preview1Z_args_getZ_iii)(u32, u32);

/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
/* export: '__wasm_call_ctors' */
extern void (*WASM_RT_ADD_PREFIX(Z___wasm_call_ctorsZ_vv))(void);
/* export: '_start' */
extern void (*WASM_RT_ADD_PREFIX(Z__startZ_vv))(void);
/* export: '__original_main' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___original_mainZ_iv))(void);
/* export: '__wasm_call_dtors' */
extern void (*WASM_RT_ADD_PREFIX(Z___wasm_call_dtorsZ_vv))(void);
/* export: '__main_argc_argv' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___main_argc_argvZ_iii))(u32, u32);
/* export: 'abort' */
extern void (*WASM_RT_ADD_PREFIX(Z_abortZ_vv))(void);
/* export: 'parse_image_header' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_parse_image_headerZ_ii))(u32);
/* export: 'malloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_mallocZ_ii))(u32);
/* export: 'parse_image_body' */
extern void (*WASM_RT_ADD_PREFIX(Z_parse_image_bodyZ_viiii))(u32, u32, u32, u32);
/* export: 'memset' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_memsetZ_iiii))(u32, u32, u32);
/* export: 'sbrk' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_sbrkZ_ii))(u32);
/* export: '__heap_base' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___heap_baseZ_i));
/* export: 'errno' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_errnoZ_i));
/* export: 'free' */
extern void (*WASM_RT_ADD_PREFIX(Z_freeZ_vi))(u32);
/* export: 'calloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_callocZ_iii))(u32, u32);
/* export: 'realloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_reallocZ_iii))(u32, u32);
/* export: 'memcpy' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_memcpyZ_iiii))(u32, u32, u32);
/* export: 'posix_memalign' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_posix_memalignZ_iiii))(u32, u32, u32);
/* export: 'aligned_alloc' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_aligned_allocZ_iii))(u32, u32);
/* export: 'malloc_usable_size' */
extern u32 (*WASM_RT_ADD_PREFIX(Z_malloc_usable_sizeZ_ii))(u32);
/* export: '_Exit' */
extern void (*WASM_RT_ADD_PREFIX(Z__ExitZ_vi))(u32);
/* export: '_exit' */
extern void (*WASM_RT_ADD_PREFIX(Z__exitZ_vi))(u32);
/* export: '__main_void' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___main_voidZ_iv))(void);
/* export: '__funcs_on_exit' */
extern void (*WASM_RT_ADD_PREFIX(Z___funcs_on_exitZ_vv))(void);
/* export: '__stdio_exit' */
extern void (*WASM_RT_ADD_PREFIX(Z___stdio_exitZ_vv))(void);
/* export: 'exit' */
extern void (*WASM_RT_ADD_PREFIX(Z_exitZ_vi))(u32);
/* export: '__dso_handle' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___dso_handleZ_i));
/* export: '__data_end' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___data_endZ_i));
/* export: '__global_base' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___global_baseZ_i));
/* export: '__memory_base' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___memory_baseZ_i));
/* export: '__table_base' */
extern u32 (*WASM_RT_ADD_PREFIX(Z___table_baseZ_i));
#ifdef __cplusplus
}
#endif

#endif  /* LIB_WASM_H_GENERATED_ */
